// <auto-generated />
namespace GoodsStore.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Dateofbirthremoved : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Dateofbirthremoved));
        
        string IMigrationMetadata.Id
        {
            get { return "201807111800513_Date of birth removed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
